export type AgentStatus = 'idle' | 'running' | 'done' | 'error';

export interface RunAnalysisInput {
  symbol: string;
  side: 'long' | 'short';
  sizeNotional: number;
  timeframe: string;
  strategyProfile: string;
  riskProfileId: string;
  notes?: string;
}

export interface AgentSummary {
  id: string;
  name: string;
  status: AgentStatus;
  shortSummary: string;
  fullSummary?: string;
}

export interface MultiAgentAnalysisResult {
  analysisSessionId: string;
  agents: AgentSummary[];
  combinedSummary: string;
}

export interface TradeEntryLeg {
  price: number;
  size: number;
  type: 'limit' | 'market';
}

export interface TradeTargetLeg {
  price: number;
  size: number;
}

export interface StopLoss {
  price: number;
  trailing?: boolean;
}

export interface TradePlan {
  tradePlanId: string;
  symbol: string;
  side: 'long' | 'short';
  sizeNotional: number;
  entries: TradeEntryLeg[];
  stopLoss: StopLoss;
  targets: TradeTargetLeg[];
  maxRiskPct: number;
  expectedRMultiple: number;
  timeHorizon: string;
  rationale: string;
  confidenceScore: number;
  createdAt: string;
}

export interface GenerateTradePlanArgs {
  analysisSessionId: string;
  constraints?: {
    maxRiskPct?: number;
    maxLeverage?: number;
    timeHorizon?: string;
  };
}

export class MultiAgentService {
  async runAnalysis(input: RunAnalysisInput): Promise<MultiAgentAnalysisResult> {
    const id = `stub-${Date.now()}`;

    const agents: AgentSummary[] = [
      {
        id: 'on_chain',
        name: 'On-Chain Analyst',
        status: 'done',
        shortSummary: `On-chain flows for ${input.symbol} look neutral to mildly bullish (stub).`,
      },
      {
        id: 'sentiment',
        name: 'Sentiment Analyst',
        status: 'done',
        shortSummary: 'Crypto sentiment is mixed, funding slightly positive (stub).',
      },
      {
        id: 'news',
        name: 'News & Events Analyst',
        status: 'done',
        shortSummary: 'No major negative headlines detected in the last 24h (stub).',
      },
      {
        id: 'technical',
        name: 'Technical Analyst',
        status: 'done',
        shortSummary: `${input.timeframe} trend is up, price trading above 50-period MA (stub).`,
      },
      {
        id: 'trader',
        name: 'Trader Agent',
        status: 'done',
        shortSummary: 'Favors a small position with tight stop and 2R+ target (stub).',
      },
    ];

    const combinedSummary =
      `Stub analysis for ${input.symbol} ${input.side} on ${input.timeframe} ` +
      `with notional ${input.sizeNotional}. ` +
      'Replace MultiAgentService with real LLM/agent orchestration for production.';

    return {
      analysisSessionId: id,
      agents,
      combinedSummary,
    };
  }

  async generateTradePlan(args: GenerateTradePlanArgs): Promise<TradePlan> {
    const now = new Date().toISOString();
    const id = `plan-${args.analysisSessionId}`;

    return {
      tradePlanId: id,
      symbol: 'BTC-USDT',
      side: 'long',
      sizeNotional: 10_000,
      entries: [
        { price: 60000, size: 0.08, type: 'limit' },
      ],
      stopLoss: { price: 57000 },
      targets: [
        { price: 63000, size: 0.04 },
        { price: 65000, size: 0.04 },
      ],
      maxRiskPct: 1,
      expectedRMultiple: 2.2,
      timeHorizon: '1d',
      rationale:
        'Stub trade plan generated by MultiAgentService. ' +
        'Wire this to your real agent graph to produce live plans.',
      confidenceScore: 0.7,
      createdAt: now,
    };
  }
}
